In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np
from sklearn.model_selection import train_test_split
digits = load_digits()
dir(digits)
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=.2)
len(x_train)


1437

In [2]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9638888888888889

In [3]:
s=SVC()
s.fit(x_train,y_train)
s.score(x_test,y_test)

C:\Users\91894\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.41944444444444445

In [12]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [24]:
# K fold
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):#dummy variables for visualising kf
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [54]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)
get_score(SVC(),x_train,x_test,y_train,y_test)
get_score(RandomForestClassifier(n_estimators=80),x_train,x_test,y_train,y_test)

C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9265442404006677

In [69]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
score_lr=[]
score_svc=[]
score_rfc=[]
for train_index,test_index in kf.split(digits.data):# for real data set
    x_train,x_test,y_train,y_test =digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(C=1),x_train,x_test,y_train,y_test))
    score_rfc.append(get_score(RandomForestClassifier(n_estimators=50),x_train,x_test,y_train,y_test))
score_lr

C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packag

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [52]:
from sklearn.model_selection import cross_val_score
a=cross_val_score(LogisticRegression(),digits.data,digits.target)
b=cross_val_score(SVC(),digits.data,digits.target)
c=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)
print(a,b,c)

C:\Users\91894\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\91894\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning

[0.89534884 0.94991653 0.90939597] [0.39368771 0.41068447 0.45973154] [0.93023256 0.95325543 0.91275168]
